version: '3.1'

services:
  postgres:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: wKHylj7AXj9HFUf
      POSTGRES_DB: socialDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase
    restart: on-failure
    volumes:
      - ./liquibase/changelogs:/liquibase/changelogs
      - ./liquibase/liquibase.properties:/liquibase/liquibase.properties
    entrypoint: ["liquibase", "--defaultsFile=/liquibase/liquibase.properties", "update"]
    depends_on:
      - postgres
  back-end:
    build: ./back-prueba-tecnica
    environment:
      DATABASE_URL: postgresql://user:wKHylj7AXj9HFUf@postgres:5432/socialDatabase?schema=public
      PORT: 3000
      SECRET_KEY: llaveprivada
      JWT_SECRET: mysecretkey
      IV: 4d165ba2d496b9025317e53e738e095d  
    container_name: back-end
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - liquibase
    command: >
      sh -c "npm run start:prod"
  
  front-end:
    build: ./front-prueba-tecnica
    container_name: front-end
    restart: always
    ports:
      - 80:80
    depends_on:
      - back-end
 

volumes:
  postgres_data:
